image: docker:latest
services:
  - docker:dind

stages:
  - build

verify:
  stage: build
  script:
    - apk update && apk add git
    - ./verify.sh
  only:
    - branches
  except:
    - master

build:
  stage: build
  image: golang:1.15
  script:
    - go build -a -mod=readonly -o /dev/null ./...
